import { NewsItem } from './types';

export const fallbackNews: NewsItem[] = [
  {
    id: '1',
    title: 'OpenAI Announces 50% Price Reduction for GPT-4 API',
    description: 'OpenAI has significantly reduced pricing for GPT-4 API calls, making it more competitive with open-source alternatives.',
    source: 'OpenAI Blog',
    url: 'https://openai.com/blog',
    publishedAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Google Expands Firebase Free Tier Limits',
    description: 'Firebase Spark plan now includes 2x the previous limits for Firestore reads and Cloud Functions invocations.',
    source: 'Google Cloud Blog',
    url: 'https://cloud.google.com/blog',
    publishedAt: '2024-01-14',
  },
  {
    id: '3',
    title: 'New Open-Source Vector Database Outperforms Pinecone',
    description: 'Turbopuffer, a new open-source vector database, shows 3x faster query times than Pinecone in benchmarks.',
    source: 'Hacker News',
    url: 'https://news.ycombinator.com',
    publishedAt: '2024-01-13',
  },
  {
    id: '4',
    title: 'Vercel Introduces New Pricing Tier for Startups',
    description: 'New Pro Startup plan offers 50% discount for companies under $1M ARR.',
    source: 'Vercel Blog',
    url: 'https://vercel.com/blog',
    publishedAt: '2024-01-12',
  },
  {
    id: '5',
    title: 'AWS Lambda Python 3.8 Runtime Deprecation Notice',
    description: 'AWS announces end-of-life for Python 3.8 Lambda runtime. Migration required by March 2024.',
    source: 'AWS Blog',
    url: 'https://aws.amazon.com/blogs',
    publishedAt: '2024-01-11',
  },
  {
    id: '6',
    title: 'Anthropic Claude 3 Offers Enterprise Pricing',
    description: 'New volume discounts available for Claude 3 API, up to 40% off for high-usage customers.',
    source: 'Anthropic',
    url: 'https://anthropic.com',
    publishedAt: '2024-01-10',
  },
  {
    id: '7',
    title: 'Supabase Launches Branching for Database Development',
    description: 'New feature allows creating database branches like Git, included in Pro plan at no extra cost.',
    source: 'Supabase Blog',
    url: 'https://supabase.com/blog',
    publishedAt: '2024-01-09',
  },
  {
    id: '8',
    title: 'Stripe Reduces International Payment Fees',
    description: 'Cross-border transaction fees reduced from 1.5% to 1% for verified businesses.',
    source: 'Stripe Blog',
    url: 'https://stripe.com/blog',
    publishedAt: '2024-01-08',
  },
  {
    id: '9',
    title: 'Hugging Face Releases Free Inference Endpoints',
    description: 'New free tier allows up to 1000 requests/day for select open-source models.',
    source: 'Hugging Face',
    url: 'https://huggingface.co/blog',
    publishedAt: '2024-01-07',
  },
  {
    id: '10',
    title: 'MongoDB Atlas Serverless Now Generally Available',
    description: 'Pay-per-operation pricing could reduce costs by up to 70% for variable workloads.',
    source: 'MongoDB Blog',
    url: 'https://mongodb.com/blog',
    publishedAt: '2024-01-06',
  },
];
